# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c303d9e9e926e0dcb884c9bb9784d59cf5b587ca7eef21744f325b13165529e1d9cba1dfe573fbe40dadfdb8a1c58b091380b9e5c5426a2423d850e0c7e4ae

test:
  secret_key_base: 937803e71d04787c833dc59a32e4db109b3a13e6a8171a49de79ed171ee5821585fea10d64cddf6ce461e41ce5341b16c953e856184864499e5a2a60b6d9df72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
